# Generated by Django 3.1.3 on 2020-11-23 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_address_oeder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='oeder',
        ),
        migrations.AddField(
            model_name='address',
            name='oreder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endpoint', to='rest.order'),
        ),
    ]
