# Generated by Django 3.1.3 on 2020-11-24 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_auto_20201123_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
