# Generated by Django 3.1.3 on 2020-11-24 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_remove_order_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductToOorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest.product')),
            ],
        ),
    ]
