# Generated by Django 3.1.3 on 2020-11-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0006_producttooorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='oreder',
            new_name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
