# Generated by Django 3.1.3 on 2020-11-24 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0007_auto_20201124_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttooorder',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest.order'),
        ),
    ]
