# Generated by Django 3.1.3 on 2020-11-24 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0009_producttooorder_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttooorder',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_order', to='rest.order'),
        ),
    ]
