# Generated by Django 3.1.3 on 2020-11-24 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0010_auto_20201124_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttooorder',
            name='products',
        ),
        migrations.AddField(
            model_name='producttooorder',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest.product'),
        ),
    ]
